### ISSUE TITLE
The latest release (v0.9.0) does not compatable with Airflow <2.4.0

### ISSUE THREAD

**Issue by ne1r0n** [bryzgaloff/airflow-clickhouse-plugin#53]
Import of `SqlSensor` is broken in `clickhouse_sql_sensor.py` because in Airflow it was moved to `airflow.providers.common.sql.sensors.sql` in v2.4.0.

**Comment by bryzgaloff** [comment]
The only version not supported now is 2.1: #52. Are you maybe using this one?

I have fixed it in this PR: #51. All the tests have passed (incl. 2.0, 2.2 and 2.3).

Could you please specify versions of Airflow, the plugin and Python to reproduce?

**Comment by ne1r0n** [comment]
Python 3.9.5
airflow-clickhouse-plugin==0.9.0
apache-airflow==2.2.5

The error I faced:
```
ModuleNotFoundError: No module named 'airflow.providers.common'
```

**Comment by bryzgaloff** [comment]
Hmmm, 3.9x2.2.5 works according to the tests: https://github.com/bryzgaloff/airflow-clickhouse-plugin/actions/runs/3497416579/jobs/5856486922

And it installs the common providers package: https://github.com/bryzgaloff/airflow-clickhouse-plugin/actions/runs/3497416579/jobs/5856486922#step:4:266

Does not your installation of `apache-airflow==2.2.5` include the common providers package? Do you have `pip install` logs for your `apache-airflow==2.2.5`? @ne1r0n

**Comment by bryzgaloff** [comment]
Though the docs say is it is preinstalled [in the latest version](https://airflow.apache.org/docs/apache-airflow/stable/extra-packages-ref.html#other-extras) but [not in v2.2.5](https://airflow.apache.org/docs/apache-airflow/2.2.5/extra-packages-ref.html#other-extras)…

Maybe we should install `apache-airflow` as `apache-airflow[common.sql]`, but I am surprised that the tests and your environment work differently.

**Comment by ne1r0n** [comment]
> Does not your installation of `apache-airflow==2.2.5` include the common providers package? Do you have `pip install` logs for your `apache-airflow==2.2.5`?

We are using docker image `apache/airflow:2.2.5-python3.8` which does not contain `apache-airflow-providers-common-sql`.

**Comment by ne1r0n** [comment]
It looks like `apache-airflow[common.sql]` won't help (it was added in v2.4.0):
```
❯ docker run -it --rm apache/airflow:2.2.5-python3.8 bash

airflow@d4da01a118dd:/opt/airflow$ pip install 'apache-airflow[common.sql]'
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: apache-airflow[common.sql] in /home/airflow/.local/lib/python3.8/site-packages (2.2.5)
WARNING: apache-airflow 2.2.5 does not provide the extra 'common.sql'
```

But `pip install apache-airflow-providers-common-sql` solves the problem.

**Comment by bryzgaloff** [comment]
I believe we should add `apache-airflow-providers-common-sql` (without specifying a version, so that it is not installed if present; and is installed otherwise) to `requirements.txt`. Could you please check if it works both with an Airflow version without `apache-airflow-providers-common-sql` installed (i.e. your 2.2.5 example) and the one with installed (i.e. when Airflow is installed explicitly, in which case it should include `apache-airflow-providers-common-sql` of an appropriate version)?

**Comment by ne1r0n** [comment]
@bryzgaloff I've tested mentioned above scenario and also ran tests with all versions of `apache-airflow-providers-common-sql`. Everything looks good and `apache-airflow-providers-common-sql` could be added to `requirements.txt`. Should I create a PR for that?

**Comment by bryzgaloff** [comment]
Thank you @ne1r0n! Just to clarify, this is an expected behaviour:
* If Airflow (of a required version) with `apache-airflow-providers-common-sql` are both installed => then when we install the plugin `apache-airflow-providers-common-sql` are not re-installed.
* If Airflow is installed, but SQL package is not (as in your example for `airflow:2.2.5-python3.8` Docker image), then `apache-airflow-providers-common-sql` are installed an plugin works fine.
* If non installed (a fresh Python container, for example), then after the installation everything works fine.

No need to test all the various versions: the PR workflow will do it itself. Just check the Airflow/SQL provider installed/not installed cases please. Cuz if SQL provider is installed, we should ideally not re-install it to both reduce the build time and not encounter any versions incompatibilities.

In fact, the above is not required, so you may proceed with a PR right away, but if you have time, please check those scenarios.

Looking forward to reviewing your PR!

**Comment by bryzgaloff** [comment]
Released as https://github.com/bryzgaloff/airflow-clickhouse-plugin/releases/tag/v0.9.1

Thank you for your contribution!
